let x=10;
let y=20;
let st="cat";
let a=true;
let b=false;
let z=x===y;
document.write(x+y);
document.write("<br>");
document.write(st+x);
document.write("<br>");
document.write(x+st);
document.write("<br>");
document.write(typeof st);
document.write("<br>");
document.write(x+y+st);
document.write("<br>");
document.write(st+x+y);
document.write("<br>");
let age=16;
document.write((age>=18)?"You can vote":"You cannot vote");
document.write("<br>");